conf_version = "v1.6.6"

[asr]
FFMPEG_PATH = "ffmpeg"
device = "cpu"
custom_output_dir = false
cache_dir = "./cache"
output_dir = "./output"
vad_model_path = "./models/silero_vad.onnx"
asr_model_provider = "sherpa"
punctuation_list = "，。；、？,.;?!"
cut = false
cut_line = 400
combine = false
combine_line = 400
max_sentence_length = 20

[asr.sherpa]
asr_model_dir = "./models/sherpa-onnx-paraformer-zh-2023-09-14"
num_threads = 2
vad_min_silence_duration = 0.25
vad_min_speech_duration = 0.25
vad_max_speech_duration = 8.0

[asr.qwen_asr]
model_dir = "./models"
preload_models = [
    "0.6b",
]
model_0_6b_path = "./models/Qwen3-ASR-0.6B-INT8-OpenVINO"
model_1_7b_path = "./models/Qwen3-ASR-1.7B-INT8-OpenVINO"
device = "CPU"
cpu_threads = 0
gpu_cache_dir = ""
forced_aligner_path = "./models/Qwen3-ForcedAligner-0.6B"
forced_aligner_device = "cuda"

[agent]
enable_tool = true
translate_provider = "llm"
user_lang = "ZH"
speaker_lang = "ZH"
faster_first_response = false
max_vision_concurrency = 4
require_detailed = false
structured_history_full_turns = 5
segment_method = "pysbd"
interrupt_method = "user"
memory_agent_profile = "profiles/baoqiao.toml"
memory_chat_profile = "profiles/congyin.toml"

[agent.chat_model]
llm_provider = "deepseek"
llm_model_name = "deepseek-v4-flash-vision-exp"
support_vision = true
thinking_mode = "disabled"

[agent.vision_model]
llm_provider = ""
llm_model_name = ""

[agent.prompts]
vision_prompt = "./prompts/vision_prompt.txt"

[[agent.llm.providers]]
name = "deepseek"
llm_api_key = ""
llm_base_url = "https://api.deepseek.com"
api_format = "chat_completion"

[[agent.llm.providers]]
name = "openai"
llm_api_key = ""
llm_base_url = "https://api.openai.com/v1"
api_format = "chat_completion"

[[agent.llm.providers]]
name = "google"
llm_api_key = ""
llm_base_url = "https://generativelanguage.googleapis.com/v1beta/openai/"
api_format = "chat_completion"

[agent.translate.deeplx]
api_key = ""

[agent.translate.llm]
model_path = "./models/qwen2.5-0.5b-instruct-q8_0.gguf"
n_gpu_layers = 0

[agent.tts]
provider = "genie_tts"
voice_assets_root = "./voices"

[agent.tts.gsv_lite]
use_bert = false

[agent.tts.genie_tts]
language = "auto"
use_roberta = false
onnx_intra_threads = 4

[agent.qwen_tts]
model_name = "0.6b"
model_0_6b_path = "./models/Qwen3-TTS-12Hz-0.6B-Base"
model_1_7b_path = "./models/Qwen3-TTS-12Hz-1.7B-Base"
device = "cuda"
warmup_cuda_graphs = true

[local_embedding]
model_path = "./models/bge-m3-q8_0.gguf"
pooling_type = "mean"
n_gpu_layers = 0

[package]
llm_translate = false
local_embedding = false
memory_bench = false
sherpa_asr = false
qwen_asr = false
gsv_lite = false
genie_tts = true
qwen_tts = false

[root]
root_dir = ""

[server]
host = "localhost"
port = 12393
config_alts_dir = "characters"
uvicorn_log_level = "warning"
live2d_render_scale = 1.0

[memory_bench]
search_limit = 10
server_api_key = ""
